disabled_rules:
- trailing_whitespace
- todo
- force_cast
- force_try
- identifier_name
- vertical_parameter_alignment
- weak_delegate
opt_in_rules:
- empty_count
- empty_string
excluded:
- Pods
- SwiftLint/Common/3rdPartyLib
- "*.generated.swift"
line_length:
    warning: 160
    error: 165
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 400
function_parameter_count:
    warning: 5
    error: 7
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 25
    error: 30
reporter: "xcode"
